name: breath
description: A new dating app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.2
  animations: ^2.0.7

  # stacked
  stacked: ^3.1.0+3
  stacked_services: ^0.9.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # code generators
  build_runner: ^2.3.3
  stacked_generator: ^0.8.3

flutter:
  uses-material-design: true
